- src/main/java/com/metamx/common/concurrent/ExecutorServices.java
Exception will raise if the service did already start
Basically, what is happening is that we have implemented a class that uses the ScheduledExecutorFactory to generate its own executors. This is done after initialization, though, so the Lifecycle has already been started. The method that is being used here to register things on the Lifecycle can only be used before it has been started. This PR is changing it to the method that can work even if the Lifecycle has already been started.
The big difference in the API is that it throws an exception, which must now be handled. Now, the only way that an exception is thrown is if the start() method throws it, the start() method does nothing here so it will not actually get thrown. Either way, we just propagate.
> Add and maybe start handler instead of add.

- src/main/java/com/metamx/common/parsers/TimestampParser.java
- src/test/java/com/metamx/common/parsers/TimestampParserTest.java
The nano timestamp parser is very basic -- it will truncate (rather
than round) a timestamp in nanoseconds to milliseconds before
returning a new DateTime representing the timestamp.
> Add nanosecond timestamp parsing

- src/main/java/com/metamx/common/StreamUtils.java
- src/test/java/com/metamx/common/StreamUtilsTest.java
The new unit tests fail without the extra flush calls.
> Add flush calls to StreamUtils to handle errors on buffered stream flushes

- src/main/java/com/metamx/common/CompressionUtils.java
- src/test/java/com/metamx/common/CompressionUtilsTest.java
This should not be merged until
https://github.com/metamx/java-util/pull/24
is in because the unit tests will not pass.
> Add flush calls in CompressionUtils to help ensure that flush errors are thrown properly

- src/main/java/com/metamx/common/lifecycle/Lifecycle.java
Useful for checking lifecycle state before calling stop on it multiple time like in CliPeon. Thus, preventing unnecessary exceptions like `Caused by: java.lang.IllegalStateException: Already closed or has not been started` to show up in task logs.
> expose started field

- src/main/java/com/metamx/common/parsers/TimestampParser.java
- src/test/java/com/metamx/common/parsers/TimestampParserTest.java
avoid string conversion while doing timestamp parsing whenever possible.
> avoid string conversion while doing timestamp parsing whenever possible

- src/main/java/com/metamx/common/guava/ConcatSequence.java
- src/test/java/com/metamx/common/guava/ConcatSequenceTest.java
previous sequence has been iterated fully.
> make ConcatSequence.toYielder(..) read next sequence only when

- src/main/java/com/metamx/common/logger/Logger.java
- src/test/java/com/metamx/common/logger/LoggerTest.java
* Fixes problems where people log by doing `log.info(message)` and `message` contains special formatting characters
> Change Logger to not try to interpret messages with no args

- src/main/java/com/metamx/common/parsers/Parser.java
- Docs for Parser
- Deprecated setFieldNames/getFieldNames. They don't appear to be used in meaningful ways anywhere in Druid, and I think are just confusing things by being on the interface.
> Parser interface docs; deprecate setFieldNames/getFieldNames.

- pom.xml
- src/main/java/com/metamx/common/parsers/JSONPathParser.java
- src/test/java/com/metamx/common/parsers/JSONPathParserTest.java
Part of a set of 3 related pull requests, addressing Druid issue:
https://github.com/druid-io/druid/issues/1839
https://github.com/metamx/java-util/pull/34   -- new JSON parser 
https://github.com/druid-io/druid-api/pull/65  -- ingestion spec modifications
https://github.com/druid-io/druid/pull/1921  -- docs and benchmark
Adds a parser using the JsonPath library that allows the user to specify fields and accessor expressions, currently used for flattening JSON during Druid ingestion.
> Add JsonPath parser

- src/main/java/com/metamx/common/lifecycle/Lifecycle.java
- src/test/java/com/metamx/common/lifecycle/LifecycleTest.java
Related to https://github.com/druid-io/druid/pull/1627
> Make Lifecycle ignore repeated stop requests

- pom.xml
- src/main/java/com/metamx/common/parsers/JSONPathParser.java
> Exclude json-smart, not needed given how we are using json-path.

- pom.xml
Without this tests complain as follows:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
> Add slf4j-simple to test scope optionally

- src/main/java/com/metamx/common/guava/ResourceClosingSequence.java
ResourceClosingSequence makes yielder for simple accumulation, which is not necessary. 
before,
```
at io.druid.query.QueryRunnerHelper$1.apply(QueryRunnerHelper.java:77)
at com.metamx.common.guava.MappingYieldingAccumulator.accumulate(MappingYieldingAccumulator.java:57)
at com.metamx.common.guava.FilteringYieldingAccumulator.accumulate(FilteringYieldingAccumulator.java:69)
at com.metamx.common.guava.MappingYieldingAccumulator.accumulate(MappingYieldingAccumulator.java:57)
at com.metamx.common.guava.BaseSequence.makeYielder(BaseSequence.java:104)
at com.metamx.common.guava.BaseSequence.toYielder(BaseSequence.java:81)
at com.metamx.common.guava.MappedSequence.toYielder(MappedSequence.java:46)
at com.metamx.common.guava.ResourceClosingSequence.toYielder(ResourceClosingSequence.java:41)
at …
```
> ResourceClosingSequence need not to create yielder for simple accumulation

- src/main/java/com/metamx/common/io/smoosh/FileSmoosher.java
CloseQuietly.close can suppress exceptions thrown by the sanity checks in SmooshedWriter.close.
> FileSmoosher: Close SmooshedWriter loudly to prevent suppressing errors.

- src/main/java/com/metamx/common/logger/Logger.java
- src/test/java/com/metamx/common/logger/LoggerTest.java
It is very easy for people unfamiliar with the logging conventions used here to swap these arguments, sometimes not yielding the desired information. This PR shows that methodology as deprecated and hopefully helps track down erroneous logging usages.
This might potentially change logging if someone had done the following:
`LOG.error("found an error: %s", someException);`
The fix would be to do something like
`LOG.error("found an error: %s", someException.getMessage());`
> Add @Deprecated catch for logging assuming slf4j convention

- src/main/java/com/metamx/common/logger/Logger.java
Fixes item mentioned in https://github.com/metamx/java-util/pull/44#issuecomment-245427523
> Simple reformat of Logger.java

- src/main/java/com/metamx/common/io/smoosh/FileSmoosher.java
- src/main/java/com/metamx/common/io/smoosh/SmooshedWriter.java
- src/test/java/com/metamx/common/io/smoosh/SmooshedFileMapperTest.java
Current `write(ByteBuffer buffer)` implementation of smoother is something like this,
```
Channels.newChannel(out).write(buffer)
```
And agagin,
```
public static ReadableByteChannel newChannel(final InputStream in) {
if (in instanceof FileInputStream &&
FileInputStream.class.equals(in.getClass())) {
return ((FileInputStream)in).getChannel();
}
return new ReadableByteChannelImpl(in);
}
```
but because `out` is a BufferedOuputStream, this call always makes wrapper which copies ByteBuffer handed over to byte[], negating good intention of using it. I think it would be better to use FileChannel directly.
> Use file channel in smoosher to minimize copy overheads

- src/main/java/com/metamx/common/CompressionUtils.java
- src/main/java/com/metamx/common/Granularity.java
- src/main/java/com/metamx/common/RetryUtils.java
- src/main/java/com/metamx/common/StreamUtils.java
- src/main/java/com/metamx/common/StringUtils.java
- src/main/java/com/metamx/common/guava/Comparators.java
- src/main/java/com/metamx/common/guava/LimitedYieldingAccumulator.java
- src/main/java/com/metamx/common/parsers/CSVParser.java
- src/main/java/com/metamx/common/parsers/DelimitedParser.java
- src/main/java/com/metamx/common/parsers/JSONPathParser.java
- src/main/java/com/metamx/common/parsers/TimestampParser.java
- src/test/java/com/metamx/common/guava/ComparatorsTest.java
- bug fix 1: https://github.com/metamx/java-util/pull/56/files#diff-aba6de6f4670f473afd1ae9ba6ef209bR86 (don't allocate `new Random()` each time we need a random value).
- bug fix 2: https://github.com/metamx/java-util/pull/56/files#diff-be255ea78e884c6ed2e259dfd9528b94R43, Comparators.inverse() is broken if the source comparator returns `Integer.MIN_VALUE`.
> Resolve most HuntBugs warnings (including two bugs fixed)

- pom.xml
for example guava 21.0 require Java 8 but we are still on Java 7
> [BACKEND-644] Updated dependencies to latest compatible versions

- pom.xml
- src/test/java/com/metamx/emitter/core/EmitterTest.java
Scala-util depends on java-util and requires netty 4.1.x (finagle is bringing it). But old async-http-client had 4.0.x, which is not compatible.
> Update async-http-client version

- src/main/java/com/metamx/emitter/core/ComposingEmitter.java
- src/main/java/com/metamx/emitter/core/ComposingEmitterConfig.java
- src/main/java/com/metamx/emitter/core/factory/ComposingEmitterFactory.java
- src/main/java/com/metamx/emitter/core/factory/EmitterFactory.java
- src/test/java/com/metamx/emitter/core/ComposingEmitterWithParametrizedTest.java
Goal: configure composing emitter using properties
The example of configuration:
```properties
com.metamx.emitter.type=composing
com.metamx.emitter.composing.noop.type=noop
com.metamx.emitter.composing.log.type=logging
com.metamx.emitter.composing.http1.type=parametrized
com.metamx.emitter.composing.http1.recipientBaseUrlPattern=http://example.com/{feed}
com.metamx.emitter.composing.http2.type=parametrized
com.metamx.emitter.composing.http2.recipientBaseUrlPattern=http://example.com/{feed}
```
> Composing emitter property-based configuration

- src/main/java/com/metamx/emitter/core/JacksonUtil.java
- src/main/java/com/metamx/emitter/core/ParametrizedUriEmitter.java
- src/main/java/com/metamx/emitter/core/ParametrizedUriEmitterConfig.java
- src/main/java/com/metamx/emitter/core/filter/BWListEventFilter.java
- src/main/java/com/metamx/emitter/core/filter/BWListEventFilterConfig.java
- src/main/java/com/metamx/emitter/core/filter/BWListEventFilterFactory.java
- src/main/java/com/metamx/emitter/core/filter/EmptyBWListEventFilter.java
- src/main/java/com/metamx/emitter/core/filter/FeedBWListEventFilter.java
- src/main/java/com/metamx/emitter/core/filter/MultiBWListEventFilter.java
- src/test/java/com/metamx/emitter/core/BWListEventFilterConfigTest.java
- src/test/java/com/metamx/emitter/core/EmittersTest.java
- src/test/java/com/metamx/emitter/core/MapEvent.java
- src/test/java/com/metamx/emitter/core/filter/EmptyBWListEventFilterTest.java
- src/test/java/com/metamx/emitter/core/filter/FeedBWListEventFilterTest.java
- src/test/java/com/metamx/emitter/core/filter/MultiBWListEventFilterTest.java
Goal: skip emitting events based on some filter
Solution: black and white value lists of event fields
This feature is needed for a composing emitter to split events pipeline among different emitters.
The example configuration of a white list of a field `feed`:
```properties
whiteList.feed=A,B,C
```
This allows emitting only events whose `feed` field is either A, B, C or omitted.
The example configuration of white lists of fields `feed`, `env`:
```properties
whiteList.feed=A,B
whiteList.env=C,D
```
This allows emitting only events whose `feed` field is either A, B or omitted and `env` field is either C,D or omitted.
The example configuration of a black list of a field `feed`:
```properties
blackList.feed=A,B,C
```
This skips emitting events whose `feed` field is either A, B or C. 
The …
> Black and white list based event filter for parametrized emitter
